### ISSUE TITLE
Add arm64 multi-arch image support for bitnami-shell

### ISSUE THREAD

**Issue by xin3liang** [bitnami/bitnami-docker-bitnami-shell#3]
There is no arm64 image in the [release image repo](https://hub.docker.com/r/bitnami/bitnami-shell/tags) yet. Can we built and push multi-arch images in there?
BTW, [minideb ](https://hub.docker.com/r/bitnami/minideb/tags) provides arm64 image already.

**Comment by carrodher** [comment]
Hi, we just created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

In this case please note bitnami/bitnami-shell is a regular image like bitnami/postgresql, bitnami/kafka or bitnami/wordpress so there are more changes required to support arm64.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
